### ISSUE TITLE
QA: EC probing tool for linux?

### ISSUE THREAD

**Issue by dumprop** [MusiKid/fancy#19]
Currently I probe the EC's registers on windows because I can't find a native solution for linux
What is the most convenient way to probe the EC's registers? (ec-probe.exe for linux)

**Comment by saidsay-so** [comment]
I am actually developing a prober along with the GUI, but you can use https://github.com/nbfc-linux/nbfc-linux.git, which includes a prober (I haven't tested it myself but it should work).

**Comment by dumprop** [comment]
> I am actually developing a prober along with the GUI, but you can use https://github.com/nbfc-linux/nbfc-linux.git, which includes a prober (I haven't tested it myself but it should work).

Wow, cool, thanks
