### ISSUE TITLE
Some troubles on fedora 35 (installing)

### ISSUE THREAD

**Issue by dumprop** [MusiKid/fancy#20]
I added copr repo, but still can't install it on fedora, seems because there no build for f35
![image](https://user-images.githubusercontent.com/34004367/140619049-1ee35800-accb-4f22-a30b-e891574c9ef1.png)
Also, installed via sources but there problems with services
![image](https://user-images.githubusercontent.com/34004367/140619082-cdc823a8-066c-49e8-a263-ae382bd38f38.png)
Seems problem in incorrect path
![image](https://user-images.githubusercontent.com/34004367/140619099-e412eb0c-66b4-4e3e-ac41-2a80cba1ede7.png)

P.S. there no problems with .rpm (it installed on f35, but there old version)

FIX: change ExecStart to /usr/local/bin/fancyd

**Comment by dumprop** [comment]
![image](https://user-images.githubusercontent.com/34004367/140656606-7035864f-d354-408e-a25e-28328447754c.png)
But there no still package for fedora
![image](https://user-images.githubusercontent.com/34004367/140656579-272c5b34-051f-457d-b439-6a0a2766d437.png)
PS in general all cool, you've done a lot of work over these few days

**Comment by saidsay-so** [comment]
I know, I had problems building Fedora packages because DNF removed command plugins.

**Comment by saidsay-so** [comment]
This time, the mirror doesn't want to download packages....

**Comment by dumprop** [comment]
> 
> 
> This time, the mirror doesn't want to download packages....

![image](https://user-images.githubusercontent.com/34004367/140658012-a8e0039e-6f99-47f1-ad6e-e3b9a2003848.png)
Package version seems strange a little bit

**Comment by saidsay-so** [comment]
@dumprop Can you confirm that it's working?

**Comment by dumprop** [comment]
> @dumprop Can you confirm that it's working?

Yes, currently seems well, thanks!

**Comment by dumprop** [comment]
@MusiKid but there are still a lot of bugs and the program almost does not work :cry:
